services:
  - type: web
    name: duck-playground
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
